version: '3.9'
services:
  liff-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/liffMemberApp # ローカルをコンテナ内にマウント
    command: sh -c "npm run dev"
    ports:
      - "5173:5173"
    stdin_open: true 